Beer.destroy_all

beers = [
  { title: 'Autumm Ember - Amber Ale', price: 2.30 , description: 'Autumn Ember Ale balances malt and hop flavors like a tightrope walker with a beer stein. With caramel, toasty, and biscuity malt notes, it\'s like a fall festival in your mouth. Pouring a rich amber hue, it looks as good as it tastes. Enjoy the smooth caramel and toasted bread flavors, perfectly balanced by a hop bitterness that\'s just the right amount of sassy. Whether you\'re kicking back or pairing it with a hearty meal, this ale is the life of the party for your taste buds.', image: 'Amber Ale.jpg', abv: 6.4, ibu: 30, hops: "Horizon, Cascade and Centennial" },
  { title: 'Majestic Midnight - Imperial Stout', price: 2.80 , description: 'Majestic Midnight Stout struts in with rich, roasted malt flavors, like a chocolate and coffee love affair. This imperial stout is as bold as it is smooth, with a touch of dark fruit sweetness. Pouring as dark as a moonless night, it\'s the perfect companion for late-night musings or impressing your beer-snob friends. It\'s big, it\'s bold, and it\'s got a royal swagger that commands respect.', image: 'Stout.jpg', abv: 7.3, ibu: 58, hops: "Magnum, Fuggle and East Kent Goldings" },
  { title: 'Liberty - American Pale Ale', price: 2.50, description: 'Liberty Pale Ale leads the charge with bright, citrusy hop notes and a smooth malt backbone. It\'s like a refreshing breeze of freedom in every sip, with zesty flavors that invigorate the senses. Pouring a golden hue, it\'s perfect for celebrating your own independence, whether you\'re at a backyard BBQ or relaxing on the porch. Raise a glass to the taste of liberty and enjoy the ride.', image: 'American Pale Ale.jpg', abv: 6.2, ibu: 41, hops: "Cascade, Citra and Amarillo" },
  { title: 'Golden Horizon - IPA', price: 2.70, description: 'Golden Horizon IPA bursts onto the scene with tropical fruit aromas and a hoppy kick that\'s as refreshing as it is bold. Imagine a sun-soaked day at the beach, but in a glass. This IPA\'s got a bitter backbone that balances out the fruity goodness, making every sip a wave of flavor. Whether you\'re a hop head or just hopping in, this IPA promises a golden experience.', image: 'IPA.jpg', abv: 6.8, ibu: 60, hops: "Citra, Mosaic and El Dorado" },
  { title: 'Harvest Glow - Pale Ale', price: 2.50, description: 'Harvest Glow Pale Ale shines with a perfect balance of malt and hop goodness. Think of it as liquid sunshine, with hints of caramel and a crisp finish that keeps you coming back for more. Pouring a radiant amber, it\'s ideal for those moments when you want to sip and savor. It\'s smooth, it\'s bright, and it\'s like a harvest festival in every glass.', image: 'Pale Ale.jpg', abv: 5.5, ibu: 30, hops: "Amarillo, Cascade and Centennial" },
  { title: 'Noble Crest - Pilsner', price: 2.10, description: 'Noble Crest Pilsner is the aristocrat of beers, with its clean, crisp taste and refined hop character. Pouring a pale golden, it\'s like sipping on a summer day with a hint of floral elegance. This pilsner is refreshingly simple yet royally satisfying, perfect for raising a glass to life\'s everyday victories. It\'s crisp, it\'s classy, and it\'s undeniably noble.', image: 'Lager.jpg', abv: 4.5, ibu: 18, hops: "Saaz, Tettnang and Hallertau" },
  { title: 'Ruby Cascade - Red Ale', price: 2.30, description: 'Ruby Cascade Red Ale dazzles with a rich, ruby hue and a flavor that\'s as bold as it is balanced. Think caramel sweetness meets a hoppy kiss, like a cozy campfire evening. Pouring with a captivating color, it\'s both a feast for the eyes and the taste buds. Whether you\'re toasting to the weekend or just winding down, this red ale is ready to impress.', image: 'Red Ale.jpg', abv: 5.5, ibu: 25, hops: "Cascade and Chinook" },
  { title: 'Sunlit Fields - Saison Pale Ale', price: 2.50, description: 'Sunlit Fields Saison brings a burst of sunshine with its fruity and spicy notes, like a picnic in a glass. With a refreshing, farmhouse character, it\'s got a hint of peppery spice that dances on the tongue. Pouring a hazy golden, it\'s the perfect beer for those lazy, sunny afternoons. It\'s lively, it\'s playful, and it\'s like a field of wildflowers in bloom.', image: 'Pale Ale.jpg', abv: 6.3, ibu: 35, hops: "Styrian Golding, Simcoe and Strisselspalt" },
  { title: 'Deep Heaven - Porter', price: 2.6, description: 'Deep Haven Porter wraps you in rich, roasted malt and chocolate flavors, like a cozy blanket by the fireplace. With hints of coffee and a smooth, velvety finish, it\'s the perfect nightcap for unwinding after a long day. Pouring a deep, dark brown, it invites you to settle in and savor each sip. It\'s comforting, it\'s robust, and it\'s your haven in a glass.', image: 'Stout.jpg', abv: 5.8, ibu: 45, hops: "East Kent Goldings and Fuggle" },
  { title: 'Pure Springs - Lager', price: 2.00, description: 'Pure Springs Lager flows with clean, crisp flavors that refresh like a dip in a cool mountain stream. Pouring a light golden, it\'s simple yet satisfying, with just enough hop bitterness to keep things interesting. This lager is perfect for any occasion, from a BBQ to a quiet evening. It\'s crisp, it\'s clear, and it\'s like a breath of fresh air in every sip.', image: 'Lager.jpg', abv: 4.2, ibu: 10, hops: "Saaz and Perle" }
]

beers.each do |beer|
  Beer.create!(beer)
end

puts "Seeded #{Beer.count} beers."
